### PR TITLE
Update initial earliest_exit_epoch calculation

### PR DESCRIPTION
**Pull request by hangleang**
reference spec change: ethereum/consensus-specs#4001

### CODE REVIEW

**Comment by hangleang** [comment]
Hi @Tumas, this spec is already implemented in devnet-5 branch, just want to know what do you think about this alter aproach

as context in devnet-5 branch:
https://github.com/grandinetech/grandine/blob/bfdaff25b4dcd889a527743f22108d7573b374f3/helper_functions/src/fork.rs#L549-L561

**Comment by Tumas** [comment]
Looks good, can you change the target to devnet5?

**Comment by hangleang** [comment]
I guess I have to change the base branch since a few commits from `develop` come along as well

**Comment by Tumas** [comment]
I've rebased devnet5 on develop, so now only the code conflicts are left.

**Comment by hangleang** [comment]
all good now

**Comment by Tumas** [comment]
It now shows 10 commits with this merge request, can you squash all your changes into 1 commit?

**Comment by hangleang** [comment]
sorry for took much time on fixing my messy commits history, done squashing those commits into one

**Comment by sauliusgrigaitis** [comment]
Thanks @hangleang , if you would like to work on Pectra then the best way would be to do Kurtosis interop with other clients ([the config](https://discord.com/channels/595666850260713488/892088344438255616/1319229366886203434) is in Ethereum R&D discord #interop chat) and debug the issues.

**Comment by hangleang** [comment]
Yes, but I will prioritize PeerDAS work since the implementation is not stable yet. If I still have some time left, I will pick up some easy tasks or quick-fix issues to work on.

**Comment by sauliusgrigaitis** [comment]
@hangleang sure, but PeerDAS is a bit stalled since everyone is focusing on Pectra.

**Comment by hangleang** [comment]
yeah, once I'm done with the rebase and switch to custody groups, and feel confident enough if the next devnet launch is announced, grandine is ready to go

**Pull request merged**
