### PR TITLE
feat: update libp2p, discv5 & fix sync with lighthouse full-node issue 

### PR DESCRIPTION
**Pull request by hangleang**
**UPDATED:** 
- libp2p -> 0.54
- discv5 -> 0.7.0
- libp2p-mplex -> 0.42.0
- fixed outbound connection issue regarding to dependency version
- fixed publish data column sidecars even though no blobs in the slot

### CODE REVIEW

**Comment by mjzk** [comment]
great to see Cargo.lock update, the current dependencies indeed has bugs

**Comment by mjzk** [comment]
eip_7594 is coming in. Is this PR a part of PeerDAS?

**Comment by hangleang** [comment]
> eip_7594 is coming in. Is this PR a part of PeerDAS?

Yes, merge to das branch

**Comment by hangleang** [comment]
closing in favor of #55

**Pull request closed without merging**
