### PR TITLE
Typo fix for building

### PR DESCRIPTION
**Pull request by TennisBowling**

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
"Instead of `--compact`" needs to be replaced with "Instead of `--profile compact`"

**Comment by sauliusgrigaitis** [comment]
> "Instead of `--compact`" needs to be replaced with "Instead of `--profile compact`"

@TennisBowling are you willing to update this?

**Comment by TennisBowling** [comment]
done!

**Comment by sauliusgrigaitis** [comment]
Looks good, please squash and rebase.

**Comment by sauliusgrigaitis** [comment]
Merged.

**Pull request closed without merging**
