### PR TITLE
[Electra] update containers ssz types based on alpha3 specs

### PR DESCRIPTION
**Pull request by hangleang**
This PR is updated based on [v1.5.0-alpha.3](https://github.com/ethereum/consensus-specs/releases/tag/v1.5.0-alpha.3) specs.

- ethereum/consensus-specs#3757
- ethereum/consensus-specs#3791
- ethereum/consensus-specs#3768
- some parts of ethereum/consensus-specs#3775, except [block-processing](https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.3/specs/electra/beacon-chain.md#block-processing) part

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Thanks @hangleang! Are you going to finish this PR to pass `v1.5.0-alpha.3` fully or is it something you are not comfortable to do?

**Comment by hangleang** [comment]
I thought to finish the `electra` spec on that alpha version. now working on `block_processing` part, but got stuck cause I'm not yet familiar with the project structure and some utilities. I would need some more time to get myself familiar. 

Is it okay for a few days delay? if not, or it'll block others work, I'm also okay to hand over.

**Comment by sauliusgrigaitis** [comment]
I think you can try for a couple of days. If no luck we can start to look at it internally.

**Comment by hangleang** [comment]
**UPDATED:** done on those remaining PRs to follow `v1.5.0-alpha3` specs, but fail on some tests. I'm working on to debugging it.

**Pull request merged**
